# DO NOT EDIT THIS FILE
#
# Please edit /boot/armbianEnv.txt to set supported parameters
#

# default values
setenv rootdev "/dev/mmcblk2p1"
setenv rootfstype "ext4"
setenv verbosity "7"
setenv bootlogo "false"
setenv fdt_addr "0x7a000000"
setenv ramdisk_addr_r "0x79000000"
setenv kernel_addr_r "0x71080000"

if test -z "${fdtfile}"; then
        setenv fdtfile "s5p4418-nanopi2.dtb"
fi

echo "Boot script loaded from SD card ${devnum}"

if ext4load mmc ${devnum}:1 ${kernel_addr_r} ${prefix}/armbianEnv.txt; then
	env import -t ${kernel_addr_r} ${filesize}
fi

if test "${bootlogo}" = "true"; then
	setenv consoleargs "splash plymouth.ignore-serial-consoles ${consoleargs}"
else
	setenv consoleargs "splash=verbose ${consoleargs}"
fi

setenv bootargs "console=ttyAMA0,115200n8 console=tty1 ${consoleargs}  root=${rootdev} rootwait rootfstype=${rootfstype} cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory printk.time=1 consoleblank=0 loglevel=${verbosity} usb-storage.quirks=${usbstoragequirks} ${extraargs}"

if ext4load mmc ${devnum}:1 ${fdt_addr} ${prefix}dtb/nexell/${fdtfile} || ext4load mmc 1:1 ${fdt_addr} ${prefix}dtb/s5p4418-nanopi2-rev07.dtb; then echo "Loading DTB"; fi
ext4load mmc ${devnum}:1 ${ramdisk_addr_r} ${prefix}uInitrd
ext4load mmc ${devnum}:1 ${kernel_addr_r} ${prefix}zImage
booti ${kernel_addr_r} ${ramdisk_addr_r} ${fdt_addr}

# Recompile with:
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr
